M48
; DRILL file {KiCad 8.0.6} date 2024-12-17T00:01:18+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-17T00:01:18+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X239.11Y-56.215
X244.89Y-56.215
T2
X106.0Y-54.0
X272.0Y-54.0
M30
